### ISSUE TITLE
Use system C++ compiler if possible

### ISSUE THREAD

**Issue by snej** [jzimmerman/langcc#11]
It would be nice if the makefile used the system’s default C++ compiler when possible. LLVM is a pretty hefty dependency to install.

Unless you’re using LLVM stuff other than Clang, it would IMHO be better just to defer to the developer and say “requires Clang vX or later”, and let them take care of installing it. In particular, most any Mac developer will already have Xcode or the Xcode CLI tools installed.

langc.cpp has the same issue: it invokes Clang with a whole bunch of hardcoded options — this is probably going to cause trouble at some point. (I’m not sure why the code has to run Clang? Other compiler-compilers I’ve used just generate source and leave it to the enclosing project to compile it.)

**Comment by jzimmerman** [comment]
Unfortunately, in addition to using LLVM's clang, I'm also using LLVM to generate stack traces. I'm currently in the process of researching other options, however. I agree LLVM is a hefty dependency if not necessary.

langcc.cpp has to run clang because, as part of compiling a language, langcc also runs the language's parser tests. This requires compiling generated code. However, this will get a lot easier if we can remove the LLVM dependency; then significantly fewer command-line flags will be required.

**Comment by jzimmerman** [comment]
More specifically, I'm looking into standalone usage of the command-line tool llvm-symbolizer, as a way to replace linking against LLVM. Am open to other suggestions, however.

**Comment by jzimmerman** [comment]
Also looking at "backward.hpp" (the library), which might be a reasonable compromise.

**Comment by jzimmerman** [comment]
Done in 50523d9.

**Comment by snej** [comment]
I have some homebrewed backtrace code that uses `<unwind.h>`, `<dlfcn.h>` and `<cxxabi.h>`. On some platforms (Linux?) there’s also `<execinfo.h>`. On Windows of course there’s a completely different API.
