### ISSUE TITLE
Comparison to K framework

### ISSUE THREAD

**Issue by JohnScience** [jzimmerman/langcc#24]
Hi, I'm on of the maintainers of [cross-lang-and-cross-platform](https://github.com/cross-lang-and-cross-platform/cross-lang-and-cross-platform) project. How does yours compare to [K framework](https://kframework.org/)?

**Comment by jzimmerman** [comment]
The K framework has a different focus than langcc; it has a basic AST generator and parser generator, as well as semantic features for working with terms in the resulting languages. By contrast, langcc generates a full compiler frontend, but does not aim to provide semantic features for working with terms in the resulting languages; this is left to the user, who can decide how they want to use the AST generated by langcc.

The most relevant direct comparison is between langcc's parser generator and K's parser generator. langcc uses an (augmented) LR parser generator (theoretical innovations described [here](https://arxiv.org/pdf/2209.08383.pdf)), which includes features such as semantic attributes and CPS transformation. Because of this, the parsers generated by langcc are highly efficient (in particular, they are guaranteed linear-time), and the languages supported are much more general (e.g., the full industrial languages Golang 1.17.8 and Python 3.9.12). K uses a GLL parser generator, which can support a more basic set of source languages, but which is not guaranteed to run in linear time, and may produce ambiguity errors at runtime.

**Comment by JohnScience** [comment]
> The K framework has a different focus than langcc; it has a basic AST generator and parser generator, as well as semantic features for working with terms in the resulting languages. By contrast, langcc generates a full compiler frontend, but does not aim to provide semantic features for working with terms in the resulting languages; this is left to the user, who can decide how they want to use the AST generated by langcc.
> 
> The most relevant direct comparison is between langcc's parser generator and K's parser generator. langcc uses an (augmented) LR parser generator (theoretical innovations described [here](https://arxiv.org/pdf/2209.08383.pdf)), which includes features such as semantic attributes and CPS transformation. Because of this, the parsers generated by langcc are highly efficient (in particular, they are guaranteed linear-time), and the languages supported are much more general (e.g., the full industrial languages Golang 1.17.8 and Python 3.9.12). K uses a GLL parser generator, which can support a more basic set of source languages, but which is not guaranteed to run in linear time, and may produce ambiguity errors at runtime.

Much love, thanks!
