### ISSUE TITLE
Requires 2 package managers on Mac / Hardcoded compiler flags

### ISSUE THREAD

**Issue by snej** [jzimmerman/langcc#3]
From the [discussion on lobste.rs](https://lobste.rs/s/rkmmjc/langcc_next_generation_compiler#c_hc1foe), by user alec:

>By default it needs both Homebrew and Ports on Mac. I’m not going to install Ports just to get libcrypto++, so I manually installed it in /usr/local, but after adding the install path to the CFLAGS/LFLAGS in the root Makefile it still failed to find libcrypto at a later stage. It turns out the compiler arguments are hard-coded [into the source code](https://github.com/jzimmerman/langcc/blob/main/src/langcc.cpp#L173).

**Comment by jzimmerman** [comment]
This is not as straightforward as it might seem; dependencies have to be hard-coded into the source code, because langcc _generates_ (and compiles) C++ from C++ itself.

However, what I have done instead is to replace libcrypto++ entirely, instead opting for a small header-only library that can be easily inlined into langcc_util.hpp, and thereby be available both to langcc and to the code that langcc generates. That should fix the issue (no more dependency on MacPorts).
